### ISSUE TITLE
Queue issue

### ISSUE THREAD

**Issue by fakesmile9704** [NoBody-UU/cuchus-music#1]
## Problem description
when i play songs or add some songs and try to see queue it gives error
Clearly and concisely describe the problem. Include any relevant context or information.

## Node.js version
v16.9.1
Specify the version of Node.js that you are using.

## Operating system
windows 11 and i tried it on docker tooo same error
Specify the operating system (e.g. Windows, macOS, Linux) that you are using.

## Bot version
latest
Specify the version of the bot that you are using.

## Steps to reproduce

1. add some songsss
2. while playing try to do [prefix]queue 
3. it will give error when playing songs but when you do the same queue command while there are no songs playing it gives no error

## Expected behavior
![image](https://user-images.githubusercontent.com/69390477/215553242-2e163065-b8f6-47dd-93aa-9e187d74e5bc.png)
![image](https://user-images.githubusercontent.com/69390477/215553336-d91c6ebd-1b23-4333-a7a9-48244bf3a1fd.png)

Describe how the code or function in question should work.

## Current behavior

Describe how the code or function is currently working. Include any error or error message that appears.

**Comment by NoBody-IDK** [comment]
i replicate the same steps, with a new bot. but i couldn't get the error you mention. 
![image](https://user-images.githubusercontent.com/58013305/216167022-74c512db-c299-4faa-8c2a-b1192ec58c28.png)


Can you tell me if you made any modifications or something apart from the installation?

**Comment by fakesmile9704** [comment]
> i replicate the same steps, with a new bot. but i couldn't get the error you mention. ![image](https://user-images.githubusercontent.com/58013305/216167022-74c512db-c299-4faa-8c2a-b1192ec58c28.png)
> 
> Can you tell me if you made any modifications or something apart from the installation?

It happens when you add like multiple songs one songs is okay but if you add a playlist and queue it wont work

**Comment by NoBody-IDK** [comment]
Fixed, 
https://github.com/NoBody-UU/cuchus-music/releases/tag/1.0.2
